AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.5
  DisplayStyleGuide: true
  DisplayCopNames: true
  Exclude:
    - .gems/**/*
    - bin/**/*
    - config/**/*
    - db/**/*
    - log/**/*
    - public/**/*
    - tmp/**/*
    - vendor/**/*
    - lib/tasks/**/*
    - spec/rails_helper.rb
    - spec/spec_helper.rb
    - config.ru
    - Guardfile
    - Rakefile
    - node_modules/**/*

Bundler/OrderedGems:
  Enabled: false

Layout/ParameterAlignment:
  EnforcedStyle: with_first_parameter

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: aligned

Layout/LineLength:
  Max: 160
  Exclude:
    - db/migrate/*.rb

Lint/MissingSuper:
  Exclude:
    - app/services/**/*

Lint/UselessAccessModifier:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FetchEnvVar:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/GlobalStdStream:
  Exclude:
    - config/**/*

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/MutableConstant:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: false

Style/Semicolon:
  AllowAsExpressionSeparator: true

Style/SingleLineBlockParams:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/NumericLiterals:
  MinDigits: 7

Style/WordArray:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Metrics/BlockNesting:
  Max: 4

Metrics/BlockLength:
  Max: 50
  Exclude:
    - spec/**/*

Metrics/ClassLength:
  Max: 250

Metrics/ModuleLength:
  Max: 250

Metrics/MethodLength:
  Max: 30
  Exclude:
    - db/migrate/*.rb

Metrics/ParameterLists:
  Enabled: false
